package com.handler;

import com.audit.AuditEvent;
import com.audit.AuditManager;
import com.bean.WrapConnect;
import io.netty.buffer.ByteBuf;
import io.netty.channel.ChannelHandlerContext;

import static com.handler.IOHandler.*;

import java.sql.SQLException;
import java.util.Arrays;

public class ConnectHandler {

    public static void handler(WrapConnect connect, ByteBuf src, ChannelHandlerContext out) throws Exception {
        String mName = readByteLen(src);
        if ("setAutoCommit".equals(mName)) {
            String bool = readByteLen(src);
            AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(), connect.getAK(), mName, bool));
            connect.setAutoCommit("true".equals(bool));
            out.write(writeByte(OK));
        } else if ("commit".equals(mName)) {
            AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(), connect.getAK(), mName));
            connect.commit();
            out.write(writeByte(OK));
        } else if ("rollback".equals(mName)) {
            AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(), connect.getAK(), mName));
            connect.rollback();
            out.write(writeByte(OK));
        } else if ("createStatement".equals(mName)) {
            String user = readShortLen(src);
            short pc = src.readByte();
            String stmtId;
            if (0 == pc) {
                AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                        user.isEmpty() ? connect.getAK() : user, mName));
                stmtId = connect.createStatement(user);
            } else if (2 == pc) {
                int resultSetType = src.readInt();
                int resultSetConcurrency = src.readInt();
                AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                        user.isEmpty() ? connect.getAK() : user, mName, resultSetType,
                        resultSetConcurrency));
                stmtId = connect.createStatement(user, resultSetType, resultSetConcurrency);
            } else if (3 == pc) {
                int resultSetType = src.readInt();
                int resultSetConcurrency = src.readInt();
                int resultSetHoldability = src.readInt();
                AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                        user.isEmpty() ? connect.getAK() : user, mName, resultSetType,
                        resultSetConcurrency, resultSetHoldability));
                stmtId = connect.createStatement(user, resultSetType, resultSetConcurrency, resultSetHoldability);
            } else throw new SQLException("createStatement param num[" + pc + "] is not exist");
            out.write(writeShortStr(OK, stmtId));
        } else if ("prepareStatement".equals(mName)) {
            String user = readShortLen(src);
            short pc = src.readByte();
            String stmtId;
            String sql = readIntLen(src);
            if (1 == pc) {
                AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                        user.isEmpty() ? connect.getAK() : user, mName, sql));
                stmtId = connect.prepareStatement(user, sql);
            } else if (2 == pc) {
                int arrSize = src.readShort();
                short type = src.readByte();
                if (0 == arrSize) {
                    if (0 != type) throw new SQLException("createPreparedStatement[autoGeneratedKeys] type[" +
                            type + "] error");
                    int autoGeneratedKeys = src.readInt();
                    AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                            user.isEmpty() ? connect.getAK() : user, mName, sql, autoGeneratedKeys));
                    stmtId = connect.prepareStatement(user, sql, autoGeneratedKeys);
                } else {
                    if (0 == type) {
                        int[] columnIndexes = readInt(arrSize, src);
                        AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                                user.isEmpty() ? connect.getAK() : user, mName, sql,
                                Arrays.toString(columnIndexes)));
                        stmtId = connect.prepareStatement(user, sql, columnIndexes);
                    } else if (1 == type) {
                        String[] columnNames = readShortLen(arrSize, src);
                        AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                                user.isEmpty() ? connect.getAK() : user, mName, sql,
                                Arrays.toString(columnNames)));
                        stmtId = connect.prepareStatement(user, sql, columnNames);
                    } else throw new SQLException("createPreparedStatement[array] type[" + type + "] error");
                }
            } else if (3 == pc) {
                int resultSetType = src.readInt();
                int resultSetConcurrency = src.readInt();
                AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                        user.isEmpty() ? connect.getAK() : user, mName, sql, resultSetType,
                        resultSetConcurrency));
                stmtId = connect.prepareStatement(user, sql, resultSetType, resultSetConcurrency);
            } else if (4 == pc) {
                int resultSetType = src.readInt();
                int resultSetConcurrency = src.readInt();
                int resultSetHoldability = src.readInt();
                AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                        user.isEmpty() ? connect.getAK() : user, mName, sql, resultSetType,
                        resultSetConcurrency, resultSetHoldability));
                stmtId = connect.prepareStatement(user, sql, resultSetType, resultSetConcurrency, resultSetHoldability);
            } else throw new SQLException("createPreparedStatement methodLength[" + pc + "] is not exit");
            out.write(writeShortStr(OK, stmtId));
        } else if ("setCatalog".equals(mName)) {
            String catalog = readByteLen(src);
            AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                    connect.getAK(), mName, catalog));
            connect.setCatalog(catalog);
            out.write(writeByte(OK));
        } else if ("setSchema".equals(mName)) {
            String schema = readByteLen(src);
            AuditManager.getInstance().audit(new AuditEvent(connect.getAddress(),
                    connect.getAK(), mName, schema));
            connect.setSchema(schema);
            out.write(writeByte(OK));
        } else throw new SQLException("connectMethod[" + mName + "] is not support");
    }
}
